<a href="https://colab.research.google.com/github/ErickNoGit/Aulas-ML/blob/main/Aula_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aula **06**

In [67]:
import numpy as np


In [68]:
minhaLista = [0,1,2,3,4,5,6,7,8]
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [69]:
meuArray = np.array(minhaLista)
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [72]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [73]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

start, stop, step

In [75]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [76]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [77]:
array3 = np.arange(0, 10, 0.5, dtype = int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
array4 = np.arange(12)
array4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [79]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [80]:
type(array4)

numpy.ndarray

In [81]:
array4.dtype #ou print(array4.dtype)

dtype('float64')

In [82]:
vetor1 = np.array([0,1,2,3,4])
print(vetor1)

[0 1 2 3 4]


In [83]:
vetor1[3]

3

In [84]:
vetor1[0:2]

array([0, 1])

In [85]:
print(vetor1[0:2])

[0 1]


In [86]:
s = np.array(['Python', 'Prfissional', 'Java', 'Água'])
s

array(['Python', 'Prfissional', 'Java', 'Água'], dtype='<U11')

In [87]:
s = np.array(['Python',1464321315, 'Prfissional', 'Java', 'Água'])
s

array(['Python', '1464321315', 'Prfissional', 'Java', 'Água'],
      dtype='<U21')

In [88]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
#vetor1[0] = 'Novo elemento'
vetor1

In [90]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])